# Generated by Django 5.1 on 2025-05-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantregistration',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participantregistration',
            name='team_status',
            field=models.CharField(choices=[('already_have', 'Already Have'), ('need_matching', 'Need Matching')], max_length=20),
        ),
    ]
